version: '3'
services:
  elk_logstash:
    image: logstash:7.10.1
    environment:
      XPACK_MONITORING_ENABLED: "false"
      ES_HOST: ${ELK_ES_HOST}
    ports:
      - "5044:5044/udp"
    volumes:
      - ./deploy/logstash.conf:/config/logstash.conf:ro
    command: logstash -f /config/logstash.conf

  elkelasticsearch:
    image: elasticsearch:7.17.5
    restart: unless-stopped
    environment:
      - discovery.type=single-node
    volumes:
      - elk_elasticsearch_value:/usr/share/elasticsearch/data
    expose:
      - "9200"
    ports:
      - "9201:9200"

  elk_kibana:
    image: docker.elastic.co/kibana/kibana:7.10.2
    environment:
      ELASTICSEARCH_HOSTS: ${ELK_ES_HOST}
    ports:
      - "5601:5601"
    depends_on:
      - elkelasticsearch

  elk_filebeat:
    image: docker.elastic.co/beats/filebeat:7.3.2
    environment:
      ELK_LOGSTASH_HOST: ${ELK_LOGSTASH_HOST}
    command: filebeat -e -strict.perms=false
    volumes:
      - /tmp/logs/nginx:/var/log/nginx:ro
      - /tmp/logs/auth_flask/:/var/log/auth_flask:ro
      - /tmp/logs/activity_api/:/var/log/activity_api:ro
      - /tmp/logs/async_api/:/var/log/async_api:ro
      - /tmp/logs/admin_panel/:/var/log/admin_panel:ro
      - /tmp/logs/worker_notifications/:/var/log/worker_notifications:ro
      - ./deploy/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
    depends_on:
      - elk_logstash
      - elkelasticsearch
      - elk_kibana
    links:
      - elk_logstash

volumes:
  elk_elasticsearch_value: